import {
  Doctor,
  Patient,
  Appointment,
  SymptomAnalysis,
  CareTimelineEvent,
  LeaveRequest,
} from './types';

export const mockDoctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    experience: 15,
    rating: 4.9,
    reviewCount: 234,
    image: '/doctors/sarah-johnson.jpg',
    availability: ['Mon', 'Wed', 'Fri'],
    nextAvailable: '2024-08-26',
    location: 'San Francisco Medical Center',
    consultationFee: 150,
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    specialty: 'Neurology',
    experience: 12,
    rating: 4.8,
    reviewCount: 189,
    image: '/doctors/michael-chen.jpg',
    availability: ['Tue', 'Thu', 'Sat'],
    nextAvailable: '2024-08-27',
    location: 'Bay Area Neurology Clinic',
    consultationFee: 175,
  },
  {
    id: '3',
    name: 'Dr. Emily Rodriguez',
    specialty: 'Pediatrics',
    experience: 8,
    rating: 4.9,
    reviewCount: 312,
    image: '/doctors/emily-rodriguez.jpg',
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    nextAvailable: '2024-08-26',
    location: 'Children\'s Health Center',
    consultationFee: 120,
  },
  {
    id: '4',
    name: 'Dr. James Wilson',
    specialty: 'Orthopedics',
    experience: 20,
    rating: 4.7,
    reviewCount: 156,
    image: '/doctors/james-wilson.jpg',
    availability: ['Wed', 'Fri'],
    nextAvailable: '2024-08-28',
    location: 'Sports Medicine Institute',
    consultationFee: 160,
  },
  {
    id: '5',
    name: 'Dr. Lisa Park',
    specialty: 'Dermatology',
    experience: 10,
    rating: 4.8,
    reviewCount: 201,
    image: '/doctors/lisa-park.jpg',
    availability: ['Mon', 'Thu', 'Fri'],
    nextAvailable: '2024-08-26',
    location: 'Skin Care Specialists',
    consultationFee: 140,
  },
  {
    id: '6',
    name: 'Dr. Robert Kim',
    specialty: 'General Practice',
    experience: 18,
    rating: 4.6,
    reviewCount: 287,
    image: '/doctors/robert-kim.jpg',
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    nextAvailable: '2024-08-26',
    location: 'Family Health Clinic',
    consultationFee: 100,
  },
];

export const mockPatients: Patient[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+1 (555) 123-4567',
    dateOfBirth: '1985-03-15',
    bloodType: 'A+',
    allergies: ['Penicillin'],
    chronicConditions: ['Hypertension'],
    emergencyContact: {
      name: 'Jane Smith',
      phone: '+1 (555) 123-4568',
      relationship: 'Spouse',
    },
  },
  {
    id: '2',
    name: 'Emma Davis',
    email: 'emma.davis@email.com',
    phone: '+1 (555) 234-5678',
    dateOfBirth: '1992-07-22',
    bloodType: 'O+',
    allergies: ['None'],
    chronicConditions: [],
    emergencyContact: {
      name: 'Michael Davis',
      phone: '+1 (555) 234-5679',
      relationship: 'Father',
    },
  },
  {
    id: '3',
    name: 'William Brown',
    email: 'william.brown@email.com',
    phone: '+1 (555) 345-6789',
    dateOfBirth: '1978-11-08',
    bloodType: 'B+',
    allergies: ['Sulfa drugs', 'Latex'],
    chronicConditions: ['Diabetes Type 2', 'Asthma'],
    emergencyContact: {
      name: 'Susan Brown',
      phone: '+1 (555) 345-6790',
      relationship: 'Spouse',
    },
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    patientId: '1',
    patientName: 'John Smith',
    doctorId: '1',
    doctorName: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    date: '2024-08-26',
    time: '10:00 AM',
    duration: 30,
    status: 'confirmed',
    urgency: 'medium',
    reason: 'Follow-up for blood pressure monitoring',
    notes: 'Patient reports mild dizziness',
  },
  {
    id: '2',
    patientId: '2',
    patientName: 'Emma Davis',
    doctorId: '3',
    doctorName: 'Dr. Emily Rodriguez',
    specialty: 'Pediatrics',
    date: '2024-08-27',
    time: '2:00 PM',
    duration: 20,
    status: 'scheduled',
    urgency: 'low',
    reason: 'Annual check-up',
  },
  {
    id: '3',
    patientId: '3',
    patientName: 'William Brown',
    doctorId: '2',
    doctorName: 'Dr. Michael Chen',
    specialty: 'Neurology',
    date: '2024-08-28',
    time: '11:30 AM',
    duration: 45,
    status: 'scheduled',
    urgency: 'high',
    reason: 'Persistent headaches and vision changes',
    notes: 'Urgent - patient reports worsening symptoms',
  },
  {
    id: '4',
    patientId: '1',
    patientName: 'John Smith',
    doctorId: '6',
    doctorName: 'Dr. Robert Kim',
    specialty: 'General Practice',
    date: '2024-08-20',
    time: '9:00 AM',
    duration: 30,
    status: 'completed',
    urgency: 'low',
    reason: 'Routine physical examination',
  },
  {
    id: '5',
    patientId: '2',
    patientName: 'Emma Davis',
    doctorId: '5',
    doctorName: 'Dr. Lisa Park',
    specialty: 'Dermatology',
    date: '2024-08-15',
    time: '3:30 PM',
    duration: 20,
    status: 'completed',
    urgency: 'low',
    reason: 'Skin rash evaluation',
  },
];

export const mockSymptomAnalysis: SymptomAnalysis = {
  id: '1',
  symptoms: [
    {
      id: '1',
      name: 'Headache',
      severity: 'moderate',
      duration: '3 days',
      description: 'Persistent throbbing pain, worse in the morning',
    },
    {
      id: '2',
      name: 'Nausea',
      severity: 'mild',
      duration: '2 days',
      description: 'Occasional nausea, especially after meals',
    },
    {
      id: '3',
      name: 'Sensitivity to light',
      severity: 'mild',
      duration: '1 day',
      description: 'Mild photophobia, manageable indoors',
    },
  ],
  urgency: 'medium',
  possibleConditions: [
    'Migraine',
    'Tension headache',
    'Sinusitis',
  ],
  recommendedSpecialist: 'Neurology',
  recommendations: [
    'Rest in a quiet, dark room',
    'Stay hydrated',
    'Monitor symptoms for changes',
    'Consider over-the-counter pain relief',
    'Schedule appointment if symptoms persist beyond 5 days',
  ],
  disclaimer: 'This AI analysis is for informational purposes only and should not replace professional medical advice. Please consult a healthcare provider for proper diagnosis and treatment.',
  analyzedAt: '2024-08-23T10:30:00Z',
};

export const mockCareTimeline: CareTimelineEvent[] = [
  {
    id: '1',
    type: 'appointment',
    title: 'Cardiology Follow-up',
    description: 'Blood pressure monitoring and medication review',
    date: '2024-08-26',
    status: 'upcoming',
    metadata: {
      doctorName: 'Dr. Sarah Johnson',
    },
  },
  {
    id: '2',
    type: 'medication',
    title: 'Prescription Refill',
    description: 'Lisinopril 10mg - 30 day supply',
    date: '2024-08-20',
    status: 'completed',
  },
  {
    id: '3',
    type: 'lab-result',
    title: 'Blood Work Results',
    description: 'Complete blood count and metabolic panel',
    date: '2024-08-18',
    status: 'completed',
    metadata: {
      results: 'All values within normal range',
    },
  },
  {
    id: '4',
    type: 'vital-signs',
    title: 'Vital Signs Check',
    description: 'Blood pressure, heart rate, temperature',
    date: '2024-08-15',
    status: 'completed',
    metadata: {
      values: 'BP: 128/82, HR: 72, Temp: 98.6°F',
    },
  },
  {
    id: '5',
    type: 'appointment',
    title: 'General Physical',
    description: 'Annual routine examination',
    date: '2024-08-20',
    status: 'completed',
    metadata: {
      doctorName: 'Dr. Robert Kim',
    },
  },
  {
    id: '6',
    type: 'note',
    title: 'Care Plan Update',
    description: 'Updated care plan based on recent physical',
    date: '2024-08-21',
    status: 'completed',
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: '1',
    doctorId: '1',
    doctorName: 'Dr. Sarah Johnson',
    startDate: '2024-09-02',
    endDate: '2024-09-06',
    reason: 'Medical conference attendance',
    status: 'pending',
    requestedAt: '2024-08-20',
  },
  {
    id: '2',
    doctorId: '3',
    doctorName: 'Dr. Emily Rodriguez',
    startDate: '2024-08-28',
    endDate: '2024-08-30',
    reason: 'Personal leave',
    status: 'approved',
    requestedAt: '2024-08-15',
  },
  {
    id: '3',
    doctorId: '4',
    doctorName: 'Dr. James Wilson',
    startDate: '2024-09-10',
    endDate: '2024-09-14',
    reason: 'Surgery recovery',
    status: 'pending',
    requestedAt: '2024-08-22',
  },
];
